build/simp-doc.spec, requirements.txt
This is a workaround for the current issue with ref2pdf where a PDF is
not generated if there are :ref: tags in your code.
In this case, the :ref: tags are stripped from the RST files prior to
generating the PDF.
This should be corrected when the bug is fixed.
This also fixes the issue with RTD failing.
SIMP-348 #close #comment 5.1.X Fix
=> SIMP-348 Fix for :ref: issue with rst2pdf

build/simp-doc.spec, requirements.txt
The current version of rst2pdf has an issue with generating PDFs with
:ref: tags.
This fixes that for the RPM version and updates the requirements file
for RTD.
SIMP-348 #comment Fixed for 4.2.X
Change-Id: I37cb20c9edefacf0971d72245ca3b2f041f25ab3
=> SIMP-348 Updated to work around :ref: bug

requirements.txt
This was causing the PIP installs to fail.
SIMP-371 #comment Fix for requirements.txt
Change-Id: I5f4af170b774ad5f36f3b63b188eef9cbea5fd27
=> (SIMP-371) Duplicate entry in requirements.txt

Changelog.rst, build/simp-doc.spec
Some manual steps need to be followed to remedy the
common::secure_mountpoints issue. These were added to the changelog.
SIMP-583 #close
SIMP-564 #close #comment Changelog Updated 4.2.X
Change-Id: I783cb27e3d63b4c24cfb0f2c5a53cf0dfc548d22
=> (SIMP-583) Update Changelog for secure_mountpoints

Guardfile, README.md, Rakefile, docs/_static/css_overrides.css
This commit adds a `Guardfile` and a new rake task `docs:server` to
support automatic html builds and ihtml review via a local web browser.
SIMP-557 #comment Added a `Guardfile` and a new rake tast `docs:server`.
SIMP-557 #comment Updated hyperlinks to theme-appropriate colors.
Change-Id: Ic272da2e54aecce42be77c9a38bcf4f81427c037
=> (SIMP-557) Add web server to rake tasks

Changelog.rst
Noted the broken symlink in the default simp environment.
SIMP-612 #comment SIMP-661 changelog update
=> (SIMP-612) Changelog update regarding SIMP-661

Changelog.rst, build/simp-doc.spec, docs/user_guide/SIMP_RPM_List.csv
The main SIMP RPM did not have the correct dependency chain in place in
the 5.1.0-0 release.
SIMP-687 #comment Doc update
=> (SIMP-687) Update to note dependency fix

docs/common/PXE_Boot.rst, docs/security_conop/Appendix_KS.rst, docs/security_conop/Appendix_SCTM.rst
A few more minor spell check errors were found and fixed.  I also removed
comments that corrected errors in PXE boot build that were fixed in
another ticket but the docs were not updated.
SIMP-586 #close
=> (SIMP-586) Documentation Spell Check Fixes

docs/security_conop/Appendix_SCTM.rst
Fixed AU-12 and IA-5 in security conop
Needed to ensure only 4 columns (dashes) per row
SIMP-940 #close
=> (SIMP-940) Fix broken table

build/simp-doc.spec, docs/common/PXE_Boot.rst, docs/installation_guide/Hiera_Overview.rst
Updated the docs to use https for the kickstart process.
SIMP-587 #comment Doc update for https change for YUM
Change-Id: I1e790d43058e79227a0ef63fb224a94ecfe07285
=> (SIMP-587) Update docs to use https for YUM

build/simp-doc.spec, docs/common/PXE_Boot.rst, docs/installation_guide/Hiera_Overview.rst
Updated the docs to use https for the kickstart process.
SIMP-587 #comment Doc update for https change for KS
=> (SIMP-587) Update docs to use https for KS

.gitignore, Rakefile, build/simp-doc.spec, docs/security_conop/Appendix_SCTM.rst
The code has been updated to both properly build the PDF and to fail if
the PDF was not built properly.
It turns out that a 0 length PDF was being output and we were not
catching this anomaly properly.
SIMP-993 #close #comment Fixed for 4.2.X
=> (SIMP-993) Update to properly build the PDF

docs/_static/css_overrides.css
SIMP-347 #comment (Finally) matched info box colors to theme in 4.2.X
Change-Id: I3ed9c92c543ed4ec7c84121078c242aff14e0a89
=> (SIMP-347) Updated "admonition" box colors

docs/conf.py
The scripts should try to pull from simp-core instead of simp-doc for
the Changelog content from now on.
SIMP-460 #comment Update to move to the proper remote repos.
=> (SIMP-460) Update to look at simp-core

build/simp-doc.spec, docs/user_guide/HOWTO/NFS.rst
Until SIMP-1400 is completed, a warning will remain in place not
to enable autofs with krb5.
SIMP-1408 #comment simp-doc warning complete
=> (SIMP-1408) Don't enable krb5 with autofs (yet!)

docs/glossary.rst, docs/index.rst, docs/security_conop/Introduction.rst, docs/security_conop/Operational_Security.rst, docs/security_conop/System_Management.rst, docs/security_conop/Technical_Security.rst, docs/security_conop/index.rst, docs/security_mapping/index.rst
The new security mapping did not have the depth of coverage that the
old SecCONOP did, therefore it has been restored to work alongside the
mapping and to ensure that adequate information is covered.
The document has been updated and as many policy references as possible
were actively cross-linked against the NIST 800-53.
SIMP-1419 #close
=> (SIMP-1419) Restored and updated the SecCONOP

docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Discard_Mail_to_Root.rst
In some cases, users will want to disable the default behavior of
sending mail to root on the local system. This HOWTO provides a
brute force way of effecting this.
SIMP-1429 #comment HOWTO for making root's e-mail die
Change-Id: I5a65102d62953b964bf15438771d65cf29d6aad5
=> (SIMP-1429) Add HOWTO for discarding root's email

docs/conf.py, docs/index.rst
The previous push to SIMP-1218 caused issues with with information loss
when publishing to ReadTheDocs. This ensures that as much information
as possible is pulled from GitHub when no other sources are available.
Much of this code should probably be consolidated into functions at
some point.
SIMP-1218 #close Fix information loss in RTD
=> (SIMP-1218) Fix issue with losing RTD information

CHANGELOG, build/simp-doc.spec
The way that the SCL repositories are installed changed and caused
issues with the EL 6 builds.
To build, you *must* have the following repositories in your Mock
configuration (this is done for you in SIMP 6 builds):
[centos-sclo-sclo]
name=CentOS-6 - SCLo sclo
baseurl=http://mirror.centos.org/centos/6/sclo/x86_64/sclo/
gpgcheck=1
enabled=1
gpgkey=https://raw.githubusercontent.com/sclorg-distgit/centos-release-sclo/master/RPM-GPG-KEY-CentOS-SIG-SCLo
[centos-sclo-rh]
name=CentOS-6 - SCLo rh
baseurl=http://mirror.centos.org/centos/6/sclo/x86_64/rh/
gpgcheck=1
enabled=1
gpgkey=https://raw.githubusercontent.com/sclorg-distgit/centos-release-sclo/master/RPM-GPG-KEY-CentOS-SIG-SCLo
SIMP-2134 #close
=> (SIMP-2134) Updated to use the new SCL repos

docs/user_guide/HOWTO/Central_Log_Collection/Logstash.rst
While I'm not sure that the elastic.co link is a permanent solution, it's much better than the lmgtfy link that is there now.
=> (SIMP-2570) replaced lmgtfy link with elastic.co link

build/simp-doc.spec, docs/conf.py, docs/glossary.rst
Before this commit, `simp-doc` builds were breaking because the version
of pip (1.4.1) that comes natively during the build with `epel-7-86_64`
is insufficient to install some of the python packages in
`requirements.txt`.  This patch fixes the issue by upgrading pip just
before installing the requirements.
SIMP-2573 #close
=> (SIMP-2573) Help mock pip to handle requirements

docs/getting_started_guide/Installing_SIMP_From_A_Repository.rst
Runpuppet can be be added without the baggage of
simp::server::kickstart, and the document reflects that.
SIMP-2731 #close
=> (SIMP-2731) Add docs on how to enable runpuppet

docs/getting_started_guide/Installing_SIMP_From_A_Repository.rst
ONLY MERGE THIS IF SIMP-2694 IS MERGED
- Removed OBE step to fix ownership of /var/run/puppetlabs/puppetserver
- Updated repo-setup text to reflect 6.X repos and the use of $releasever
yum variable.
- Removed references to earlier versions of SIMP, as these instructions
may not apply.
SIMP-2694 #close
=> (SIMP-2694) Remove OBE chown step in RPM install

docs/user_guide/HOWTO/Redundant_LDAP.rst
- updated the documentation for redundant LDAP server for
simp V6.
SIMP-2768 #comment  updated the documentation, still need to update tests
=> (SIMP-2768) Update Redundant LDAP server Document

docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Puppetmaster_Backup.rst, docs/user_guide/HOWTO/Work_With_Rsync.rst
Adds full documentation on using SIMP Rsync and some minor
instructions on performing a backup/restore of critical SIMP files.
SIMP-2819 #close
=> (SIMP-2819) Document how to use SIMP Rsync

docs/getting_started_guide/ISO_Build/Building_SIMP_From_Tarball.rst, docs/getting_started_guide/ISO_Build/Environment_Preparation.rst
The commit updates minor portions of the "Build a bootable SIMP DVD"
section in preparation for the 6.0.0-0 release of SIMP.
SIMP-2918 #close
=> (SIMP-2918) Update bootable DVD content & links

docs/getting_started_guide/Introduction.rst, docs/help/FAQ.rst, docs/help/FAQ/Root_Logins.rst, docs/user_guide/HOWTO/Managing_Workstation_Infrastructures.rst
The fact that root logins were not allowed at the console in SIMP 6 was
not well documented.
This adds a FAQ entry and ensures that it is referenced prominently in
the Getting Started Guide.
Also fixed some heading inconsistency in the Managing Workstation
Infrastructures document.
SIMP-3254 #close
=> (SIMP-3254) Added FAQ regarding Root Logins

CHANGELOG, docs/getting_started_guide/ISO_Build/Building_SIMP_From_Source.rst
- Ensured no invalid refs to CentOS 6.8
- Updated building from source docs to reference the
release_mapper
SIMP-3186 #close
=> (SIMP-3186) 6.9 doc updates

docs/getting_started_guide/Installing_SIMP_From_A_Repository.rst, docs/help/Public_Resources.rst
* Changed the `runpuppet` download URL to use HTTPS instead of HTTP to
be in line with best practices.
* Updated the security help link to point to the mailing list directly
SIMP-3387 #close
=> (SIMP-3387) Ensure that users use https for runpuppet

docs/help/FAQ/Selinux.rst, docs/security_conop/Technical_Security.rst, docs/security_mapping/components/sudosh/session_audit/control.rst, docs/user_guide/HOWTO/Manage_TPM.rst, docs/user_guide/SIMP_Administration/General_Administration/Session_Auditing.inc
This patch fixes the incorrect assertion that SIMP uses `sudosh` for 
keystroke logging.  It also fixes minor errors and warnings that affected
compilation.
SIMP-3617 #close
=> (SIMP-3617) Correct session auditing docs

docs/user_guide/HOWTO/NFS.rst
- documented know problem with autofs over stunnel that affects
the simp_nfs profile module on CentOS 6.9
SIMP-3717 #close
SIMP-3719 #close
=> (SIMP-3435) CentOS 6.9 NFS problems

Gemfile, Rakefile, build/simp-doc.spec, docs/conflib/get_simp_version.py, docs/conflib/release_mapping.py
- Fixed bugs that prevented simp-doc RPM from building.
- Fixed bug in which the simp-doc RPM was not built using local
simp-core.
- Removed OBE simp5/simp6 flags in simp-doc.spec
***This requires simp-rake-helpers >=5.0.2***
SIMP-3837 #close
SIMP-3811 #comment simp-doc fix
=> (SIMP-3837) simp-doc: Fix broken RPM build

docs/conf.py
Added support for a ``SIMP_FAST_DOCS`` environment variable that, when
set to ``true``, will exclude certain long-running sections of the
documentation from being included.
In general, this has shown a 66% speed up in the RPM build process but
should only be used for testing the RPM build to identify catastrophic
failures.
=> (SIMP-3811) SIMP_FAST_DOCS=true flag added

CHANGELOG, docs/user_guide/HOWTO/NFS.rst
- autofs does not work over stunnel in CentOS 7.4 because of a
Redhat bug.  Updated know issues section in HOWTO/NFS to
inform users
SIMP-3984 #close
SIMP-3977 #close
=> (SIMP-3977) SIMP_NFS tests failing

docs/user_guide/Certificates/Certificates.inc, docs/user_guide/Certificates/Official_Certificates.inc, docs/user_guide/Client_Management.rst, docs/user_guide/SIMP_Administration/General_Administration/Certificate_Management.inc, docs/user_guide/Troubleshooting/Puppet_Certificate_Issues.rst
simp_options::pki
- updated documentation
- consolidate FakeCA documentation in one place.
- remove comment about auto for gencerts because it doesn't do anything.
SIMP-4443 #close
SIMP-4474 #close
SIMP-4475 #close
=> (SIMP-4443) Document Difference between simp and true in

requirements.txt
There is a bug in `reportlab` 3.5.0 that renders it inoperable with
`rst2pdf`.
=> (SIMP-4989) Pin reportlab to 3.4.0

CHANGELOG, Gemfile, docs/getting_started_guide/Just_Install.rst, docs/glossary.rst, docs/index.rst, docs/user_guide/Client_Management.rst, docs/user_guide/PXE_Boot.rst, docs/user_guide/Upgrade_SIMP/Version_Maps/6.1.0_6.2.0.inc, docs/user_guide/Upgrade_SIMP/Version_Specific_Upgrade_Instructions.rst
-This updates the docs for UEFI PXE booting.
-It adds an upgrade section for 6.1.0 - 6.2.0 and documents files
that need to be updated in and existing system.
-Renames For he IMpatient to Quick Start
SIMP-5106 #close
SIMP-5107 #close
SIMP-4557 #close
=> (SIMP-4958) Updates docs for EFI tftpboot

docs/user_guide/SIMP_Package_Data.rst
-  The documentation was fixed to referred to how extract the package
list previously so this is OBE.  I just fixed a broken link in
in the page.
SIMP-2986 #close
SIMP-5290 #close
=> (SIMP-2986) Update Packages in Documentation

docs/user_guide/Troubleshooting.rst, docs/user_guide/Troubleshooting/Puppet_Issues.rst, docs/user_guide/Upgrade_SIMP/Version_Maps/6.2.0_6.3.0.inc, docs/user_guide/Upgrade_SIMP/Version_Specific_Upgrade_Instructions.rst
Puppet 5.5.6+ marks the `[master]` section's `ca` setting as deprecated,
causing every `puppet` run to emit an eye-catching warning when the
configuration is set in `puppet.conf`.  **simp/pupmod** has been updated
to accomodate this, but in some circumstances it is unavoidable.
This patch documents the issue, provides a (heavy-handed) workaround, and
draws attention to it in the 6.3.0 upgrade guide.
SIMP-5456 #close
=> (SIMP-4546) Document unavoidable `ca` warning

docs/user_guide/HOWTO/NFS.rst
When following these instructions I noticed that the export path for the example share with stunnel was incorrectly pointing to `/home` instead of `/share1` which confused me for a moment. I tested it out and it seems to me that it is in fact incorrect.
=> Fix incorrect path for NFS server export

docs/changelogs/latest.rst
- Fix code block in SIMP-6.3.0-0 errata to prevent overextended code
block and extra whitespace/characters
=> (SIMP-MAINT) Fix code block for 6.3.0-0 Errata

docs/changelogs/latest.rst
- updates italics (should have been double backticks for code line) to a code block for better appearance.
=> (SIMP-MAINT) Fix code block in errata

CHANGELOG, docs/user_guide/User_Management/LDAP.rst
sed command in 4.8.1.1 Prepare SIMP ldifs had an escaped asterisk. The
command errors with: "sed: can't read *.ldif: No such file or
directory" when run this way. The command runs find with an unescaped
asterisk.
=> (SIMP-6323 ) Fixed typo in Prepare SIMP ldifs

CHANGELOG, docs/user_guide/User_Management/Local_Users.rst
The Managing Local/Service Users page indicated to save the account.pp
files in /etc/puppetlabs/code/environments/simp/modules/site/. This path
is incomplete and needs manifests/ at the end.
=> (SIMP-6330) Incomplete path for saving account.pp files.

CHANGELOG, docs/getting_started_guide/System_Requirements.rst
With less than 3.4 GB of RAM+swap the puppet database and puppet server
may not start. /etc/sysconfig/puppetdb requires 1516m and
/etc/sysconfig/puppetserver requires 1896m. This comes out to just over
3.3 GB.
If -Xms is lowered, it is possible to have a machine with less than 3.4
GB of RAM+swap, but performance will be impacted, and at some point
there will be too little allocated memory for the puppet database/server
to run.
=> (SIMP-6328) Added official hardware requirement for RAM plus swap

CHANGELOG, docs/getting_started_guide/Installation_Options/ISO/Installation_Advanced_Topics/Disk_Partitioning.rst, docs/glossary.rst, docs/user_guide/HOWTO/Managing_Workstation_Infrastructures.rst, docs/user_guide/HOWTO/NFS.rst, docs/user_guide/HOWTO/Redundant_LDAP.rst, docs/user_guide/PXE_Boot.inc, docs/user_guide/SIMP_Administration/General_Administration/Nightly_Updates.inc
- Removed all calls to the 'site' module specifically
- Rebranded references to the 'site' module as a convienient place holder and
added appropriate glossary terms.
- Added glossary terms for:
- Puppet Module
- Puppet Namespace
- Site Profile
SIMP-6363 #close
=> (SIMP-6363) Refactor references to the 'site' mod

docs/glossary.rst, docs/user_guide/Upgrade_SIMP/Version_Maps/6.3.3_6.4.0.inc
- Updated upgrade guide to use --local-modules env option.
- Fixed warning in glossary
SIMP-6681 #comment simp-doc
=> (SIMP-6681) Use --local-modules env option in upgrade instructions

docs/user_guide/Upgrade_SIMP/Version_Maps/6.3.3_6.4.0.inc
One example was correct.  The other left the umask inappropriately
set.
=> (SIMP-MAINT) Fix r10k sg example

docs/changelogs/latest.rst, docs/help/FAQ/10_Password_Complexity.rst, docs/help/FAQ/40_Audit_Syslog.rst, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Disable_Ssh.rst, docs/user_guide/HOWTO/IPA_Clients.rst, docs/user_guide/HOWTO/Manage_TPM.rst, docs/user_guide/HOWTO/Managing_Workstation_Infrastructures.rst, docs/user_guide/PXE_Boot.inc, docs/user_guide/SIMP_Administration/Classification_and_Data/Assigning_Classes_to_Nodes.inc, docs/user_guide/Upgrade_SIMP/Version_Maps/6.3.3_6.4.0.inc, docs/user_guide/User_Management/Local_Users.rst, docs/user_guide/User_Management/SSSD.rst
* Removed trailing whitespace
* Minor documentation updates
* Clarified assigning classes to use simp::classes
* Modified 'classes:' to be 'simp::classes:' except where other PRs are
addressing the change
SIMP-6579 #comment various cleanup items
=> (SIMP-6579) Various cleanup items

docs/changelogs/latest.rst
The docs have already been updated with complete instructions
on how to handle the possible root lockout scenario.  This update
simply notes the bug fix to rubygem-simp-cli.
SIMP-6900 #close
=> (SIMP-6900) Update docs possible root lockout

docs/changelogs/latest.rst, docs/user_guide/Initial_Server_Configuration/Advanced_Configuration.inc
- Documented all the SIMP Puppet 3 API functions to be
deprecated, so they can be removed in the next release.
(Removal necessary for full Puppet 6 support).
- Fixed a random malformed sentence
SIMP-6915 #close
=> (SIMP-6915) Document deprecated functions

.travis.yml, requirements.txt
This patch fixes an issue that where `sphinx-build -b pdf` would fail
while processing inline PNG images.  This problem would cause both `rake
docs:pdf` and simp-doc RPM builds to fail.
It also adds an optional "Sphinx PDF build" step to the Travis CI
pipeline, which can be enabled by setting `env: BUILD_PDF=yes`.
SIMP-7017 #close
=> (SIMP-7017) Fix docs:pdf errors on PNG images

CHANGELOG, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Alternate_SIMP_Config_Environment.rst, docs/user_guide/Initial_Server_Configuration.rst
Added a HOWTO for using an alternate target environment during `simp
config` and `simp bootstrap`
SIMP-6936 #comment Added HOWTO for 'simp config' environment change
=> (SIMP-6936) HOWTO for simp config env change

docs/contributors_guide/maintenance/ruby_gem_release_procedures/Release_GitHub_Deploy_RubyGems_org.rst
pkg:compare_create_tag_changelog has worked on asset repos for
quite some time! This update uses it to simplify the release
procedures.
=> (SIMP-MAINT) Update asset release procedures

docs/contributors_guide/maintenance/ruby_gem_release_procedures/Release_GitHub_Deploy_RubyGems_org.rst
This reverts commit 26dfdb49af7c0b8b3d72010958a312e319986e01.
The `pkg:create_tag_changelog` task is available for Puppet modules, but
not RubyGems.
=> (SIMP-MAINT) Revert changes from #376

docs/user_guide/HOWTO/Work_With_Rsync.rst, docs/user_guide/PXE_Boot.inc
* Ensure that users are aware that all links in the 'rsync' space must
be relative
SIMP-8381 #close
=> (SIMP-8381) Clarify rsync space links

docs/user_guide/Initial_Server_Configuration.rst
* Added a warning telling users that they need to unpack the SIMP ISO if
the original system was not built from a SIMP ISO.
SIMP-8395 #close
=> (SIMP-8395) ISO unpack_dvd note regarding SIMP ISO

docs/changelogs/latest.rst, docs/user_guide/HOWTO/Disable_Ssh.rst, docs/user_guide/Initial_Server_Configuration.rst, docs/user_guide/Initial_Server_Configuration/Prevent_Lockout_on_Puppetserver.inc, docs/user_guide/Troubleshooting/My_Services_Are_Dying.rst
* Fixed errors in the "Prevent Lockout from the SIMP Server..." section.
- Path to server YAML file was missing 'hosts'.
- ``passwd => false`` needed to be added to the ``sudo::user_specification``
when the user does not log in with a password.
- Example metadata.json file was malformed and missing the simplib dependency.
Also, since versions change frequently, removed the version specifications.
- Changed the OBE 'classes' hieradata key to 'simp::classes'.
* Added missing information to "Prevent Lockout from SIMP Server..." section.
- Added a description of the one other lockout that is possible.
- Added verification that the create manifest yields no errors or warnings.
- Added verification of ssh login in sudo access before reboot.
* Added a note about required use of IP addresses in …
=> (SIMP-8456) Prevent lockout instructions are incorrect

docs/user_guide/HOWTO/Manage_TPM.rst, docs/user_guide/HOWTO/Managing_Workstation_Infrastructures.rst, docs/user_guide/HOWTO/NFS.rst, docs/user_guide/HOWTO/Redundant_LDAP.rst, docs/user_guide/Initial_Server_Configuration/Prevent_Lockout_on_Puppetserver.inc
Added:
* Modified the NFS documentation to warn about breaking changes in
version 7 of simp-nfs and simp-autofs
Fixed:
* Fixed some code examples
* Directly linked to SIMP support tickets
Notes:
* Validated that the NFS and Autofs updates in the changelog for 6.5.0
reflect the breaking changes well
SIMP-8377 #close
=> (SIMP-8377) Updated NFS documentation

docs/changelogs/latest.rst
Changelog updates:
* Entries for latest released version of simp/simp
* Entries for released version of simp/tftpboot. Removed discussion
of a change that was reverted (rsync permissions).
* Fixed a few typos/unclear passages.
* Standardized reference to hiera as "Hiera" to match Puppet
documentation.
* Used new Sphinx roles. Wasn't sure what to do with a couple of
types of text that are not covered by the current set of roles.
* Snippets of text emitted from a warning message:  Used double
backticks.
* Facts: Used :code:
* Strings that would end up in application configuration files:
Used single quotes.
* YAML keys: Used single quotes except when talking about adding
a class to `simp:classes` in Hiera.
* Dynamic libraries: Used single quotes.
* Puppet environment name: Used single quotes …
=> (SIMP-8480) Update changelog for 2 components + use roles

docs/_extensions/simp_roles.py
The SIMP docs now prefer the forward slash delimiter to separate
Puppet modules' `org/name` references.  This patch adds a compiler
warning to the `:pupmod:` role that points out when the wrong format
is being used, and demonstrates the correct format.
[SIMP-8609] #comment :pupmod: role compiler warns on wrong delimiter
[SIMP-8609]: https://simp-project.atlassian.net/browse/SIMP-8609
=> (SIMP-8609) Add compiler warning for wrong delim

docs/HOWTO/00_Accounts_and_Access/Configure_Ssh.rst, docs/HOWTO/00_Accounts_and_Access/IPA_Clients.rst, docs/HOWTO/10_SIMP/Modify_Puppet_Cron.rst, docs/HOWTO/20_Puppet/Block_or_Cache_Facts.rst, docs/changelogs/latest.rst, docs/user_guide/Upgrade_SIMP/Version_Maps/6.4.0_6.5.0.inc
Updates:
* List SIMP resource parameters that cannot contain hostnames when
firewalld is enabled.
* Remove :pupmod: errors used to demonstrate that role's validation
logic.
SIMP-8484 #close
=> (SIMP-8484) List parameters affected by firewalld limitations

docs/changelogs/latest.rst
Updated:
* SIMP 6.5.0 release qualifier is now Beta
* Documented fix in pupmod-simp-iptables 6.5.3
* Documented fix in pupmod-simp-pupmod 8.1.1
* Documented update in simp-rsync-skeleton 7.0.4
SIMP-8480 #comment update 3
=> (SIMP-8480) Update changelog with 3 patches for Beta

docs/contributors_guide/Documentation.rst, requirements.txt
This patch updates `requirements.txt` to use sphinx-csv-filter 0.3.0+
and converts the `csv-filter` directives in the Contributors' style
guide to use the (much clearer) `:include:` filter.
=> (SIMP-MAINT) Switch csv-filter to :include:

docs/changelogs/latest.rst
This patch documents EL8 client limitations in the 6.5.0 changelog
[SIMP-8579] #close #comment Document EPEL8 and EL8 base mirror req
[SIMP-8615] #close #comment Document modular dnf errata for EL8
SIMP-8580 #close
[SIMP-8579]: https://simp-project.atlassian.net/browse/SIMP-8579
[SIMP-8615]: https://simp-project.atlassian.net/browse/SIMP-8615
=> (SIMP-8580) Document EL8 dnf and PXE client limits

CHANGELOG, docs/HOWTO/10_SIMP/Disable_the_Firewall.rst, docs/changelogs/latest.rst
Changed:
- Updated the changelog docs to note that firewalld is now the default
for new installations
Added:
- Added a HOWTO for fully disabling the system firewall
SIMP-8616 #comment related doc updates
=> (SIMP-8616) Firewall doc updates

docs/changelogs/latest.rst
puppet/gitlab and simp/simp_gitlab have been updated for EL8
and are now included in the SIMP 6.5.0 ISO.
=> (SIMP-MAINT) Remove OBE gitlab references

docs/conf.py, docs/getting_started_guide/Installation_Options/ISO/ISO_Build/Environment_Preparation.rst
This patch brings the environment prep docs' Ruby version in line with
Puppet 6
[SIMP-9121] #close
[SIMP-9121]: https://simp-project.atlassian.net/browse/SIMP-9121
=> (SIMP-9121) Bump ruby version to 2.5.7

docs/HOWTO/10_SIMP/Enable_STIG_Mode.rst
Updated the STIG enforcement docs to make it easier for users to work
with the system after SELinux is enabled properly.
SIMP-9629 #close
=> (SIMP-9629) Correct STIG sudo docs

docs/FAQ/Puppet.rst, docs/user_guide/Initial_Server_Configuration.rst
This patch reverts references to `serverport` back to `masterport` and updates some double-backticks with ReST roles.
=> (SIMP-MAINT) Revert serverport to master

.github/workflows/pr_glci.yml, .github/workflows/pr_glci_cleanup.yml, .github/workflows/pr_glci_manual.yml, .github/workflows/release_rpms.yml, .github/workflows/tag_deploy_github-rpms.yml, .github/workflows/validate_tokens_asset.yml
This patch ensures that a GitHub release will trigger the `release_rpm`
GHA workflow.
The patch enforces a standardized asset baseline using simp/puppetsync,
and may apply other updates to ensure conformity.
[SIMP-10393] #close
[SIMP-10392] #comment Add `release_rpms` to simp-doc
[SIMP-10393]: https://simp-project.atlassian.net/browse/SIMP-10393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIMP-10392]: https://simp-project.atlassian.net/browse/SIMP-10392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (SIMP-10392) GHA: Trigger `rpm_release` workflow

.github/workflows/release_rpms.yml, .github/workflows/tag_deploy_github-rpms.yml
This commit rolls up various improvements to the GHA tag & release
workflows, particularly:
* Tagged releases build a matrix of RPMs: (EL8 *and* EL7)
* Tagged release logic supports pre/post-release tag formats
* New arguments in `release_rpms.yml`: `path_to_build` and `verbose`
* Ensure jobs run on `ubuntu-latest`
* Fixes for variable edge cases and inter-job dependencies
The patch enforces a standardized asset baseline using simp/puppetsync,
and may apply other updates to ensure conformity.
[SIMP-10637] #close
[SIMP-10633] #comment Add `release_rpms` to simp-doc
[SIMP-10637]: https://simp-project.atlassian.net/browse/SIMP-10637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SIMP-10633]: …
=> (SIMP-10633) Update standardized assets
