.travis.yml, docs/index.rst, docs/installation_guide/Hiera_Overview.rst, docs/installation_guide/PXE_Boot.rst, docs/installation_guide/SIMP_Server_Installation.rst, docs/license.rst, docs/user_guide/FAQs/Centralized_Logging.rst, docs/user_guide/FAQs/Changing_Puppet_Masters.rst, docs/user_guide/FAQs/Override_Security_Module.rst, docs/user_guide/FAQs/Puppet_Server_NAT.rst, docs/user_guide/FAQs/Redundant_LDAP.rst, docs/user_guide/FAQs/SFTP_Restricted_Accounts.rst, docs/user_guide/Kerberos.rst, docs/user_guide/Logstash.rst, docs/user_guide/Managing_Workstation_Infrastructures.rst, docs/user_guide/Maximum_Nodes.rst, docs/user_guide/Openstack_Integration.rst, docs/user_guide/PXE_Boot.rst, docs/user_guide/SIMP_Administration.rst, docs/user_guide/Upgrading_SIMP.rst, docs/user_guide/User_Management.rst, docs/user_guide/jenkins_scripts.rst
Fixed some typos on original documentation -- not complete
SIMP-103 #comment Fixed some of the typoes
=> (SIMP-103) Make first set of corrections on docs

docs/common/Introduction.rst, docs/conf.py, docs/index.rst, docs/installation_guide/SIMP_Server_Installation.rst, docs/installation_guide/index.rst, docs/user_guide/Upgrading_SIMP.rst
Also reordered sections and made a change to a file
and prototyped conf.py with version number
SIMP-317 #close
=> (SIMP-317) making password its own section

build/simp-doc.spec
Missed updating the Release number in the RPM spec file.
SIMP-463 #comment Updated RPM Spec File
Change-Id: I640ec3de3c2dbac73b40088778f16886c53087b2
=> (SIMP-463) Updated version number in RPM spec

docs/user_guide/FAQs/Local_User_Access/SSH_Keys.rst, docs/user_guide/User_Management.rst
=> (SIMP-557) Fix PAM info to be more visible

docs/common/Client_Management.rst, docs/common/Glossary.rst, docs/common/PXE_Boot.rst, docs/conf.py, docs/installation_guide/Hiera_Overview.rst, docs/installation_guide/Installation_Miscellaney.rst, docs/installation_guide/PXE_Boot.rst, docs/installation_guide/SIMP_Server_Installation.rst, docs/installation_guide/index.rst, docs/user_guide/PXE_Boot.rst, docs/user_guide/index.rst
This update rewrote the PXE boot section and put it in order.
This also updates the variable lists for the simp config process
although more work needs to be done on this.
SIMP-323 #close #comment Updated for 4.2.X
Change-Id: I5aca40c893cd4349df87d48c924455293fa9de6c
=> (SIMP-323) Documentation updates

build/simp-doc.spec, docs/conf.py
The PDF generation got commented out at some point.
SIMP-617 #comment Re-enable PDF generation
Change-Id: I5ec0e7dfd1c9f9749ebb36c38041d4312417708a
=> (SIMP-617) Fix Doc Build Scripts

build/simp-doc.spec, docs/conf.py
The PDF generation got commented out at some point.
SIMP-612 #comment Re-enable PDF generation
Change-Id: I5628262f89c51e6729c2daeae6ab5babe69a25e8
=> (SIMP-612) Fix Doc Build Scripts

Changelog.rst
Added the Changelog updates for simplib.
SIMP-625 #comment Changelog update
=> (SIMP-625) Updated changelog for simplib

Changelog.rst
Noted the broken symlink in the default simp environment.
SIMP-617 #comment SIMP-661 changelog update
=> (SIMP-617) Changelog update regarding SIMP-661

docs/common/Client_Management.rst, docs/common/Glossary.rst, docs/installation_guide/Hiera_Overview.rst, docs/installation_guide/SIMP_Server_Installation.rst, docs/security_conop/Appendix_SCTM.rst, docs/user_guide/Logstash.rst
This does minor updates to the documents to fix spell check errors.
SIMP-586 #close - all relevant changes were made.
=> (SIMP-586) Spell Check the documentation

Changelog.rst, build/simp-doc.spec
The documentation was not properly updated for 5.1.0-0.
SIMP-683 #close
=> (SIMP-683) Documentation update for 5.1.0-1

Changelog.rst, build/simp-doc.spec
4.2.0-1 Doc update
SIMP-699 #comment Doc update for 4.2.0-1
=> (SIMP-699) Update to docs for 4.2.0-1

Changelog.rst
Updated the changelog for 4.2.0-2
SIMP-869 #close
SIMP-832 #comment Changelog Update
=> (SIMP-869) Changelog Update

Changelog.rst
Converted to consistent RST format.
SIMP-874 #close
=> (SIMP-874) Changelog Updated

Changelog.rst
The NFS tests resulted in a few additional module improvements.
SIMP-874 #comment NFS test result updates
=> (SIMP-874) Updated with NFS test resulting changes

Changelog.rst
The NFS tests resulted in a few additional module improvements.
SIMP-869 #comment NFS test result updates
=> (SIMP-869) Updated with NFS test resulting changes

build/simp-doc.spec, docs/security_conop/Appendix_KS.rst
Mirror changes from pupclient_x86_64.cfg.
SIMP-587 #close
=> (SIMP-587) Update to reflect SSL kickstart repos

docs/_static/css_overrides.css
SIMP-347 #comment (Finally) matched info box colors to theme in 5.1.X
Change-Id: Ifec9aec1f737590c26f10700b9214800b22c179a
=> (SIMP-347) Updated "admonition" box colors

README.md
Removed the explicit 5.1.X reference from the README
SIMP-460 #comment Updated README references
=> (SIMP-460) Updated README

build/package_metadata.yaml
Missed this in the last push.
SIMP-1112 #close
=> (SIMP-1112) Update to build docs for all releases

Gemfile, Rakefile, docs/conf.py, docs/getting_started_guide/Building_From_Source.rst, docs/getting_started_guide/Environment_Preparation.rst, docs/getting_started_guide/Installation_From_Packages.rst, docs/getting_started_guide/Introduction.rst, docs/getting_started_guide/index.rst, docs/glossary.rst, docs/index.rst
Started to restructure some of the docs and updated the conf.py to be a
bit more intelligent.
SIMP-1146 #comment Added dev guide and started restructuring
=> (SIMP-1146) Added dev guide and restructuring

docs/conf.py, docs/index.rst
* RTD now builds properly from files all over the Internet
* Removed the Getting Started stuff from the index because it's not
ready
SIMP-1146 #comment RTD Fixes
=> (SIMP-1146) Fixed conf.py for RTD

CHANGELOG, build/simp-doc.spec
* Fixed the spec file to handle the add on files properly
* Split out the CHANGELOG for pretty
SIMP-1411 #close
=> (SIMP-1411) Updated the doc RPM spec

docs/glossary.rst, docs/installation_guide/Introduction.rst, docs/installation_guide/SIMP_Server_Installation.rst, docs/security_conop/Technical_Security.rst, docs/security_mapping/components/openldap/authenticator_management/control.rst, docs/user_guide/FAQ.rst, docs/user_guide/FAQ/Password_Complexity.rst, docs/user_guide/Troubleshooting/Why_Cant_I_Login.rst
* Documented SSSD needing a good password prior to letting you login
* Added a password complexity FAQ
* Linked to the password complexity FAQ where appropriate
* Added a glossary entry for SSSD
SIMP-1328 #close
SIMP-1406 #close
=> (SIMP-1328) Document SSSD password insanity

docs/conf.py, docs/glossary.rst, docs/installation_guide/SIMP_Server_Installation.rst, docs/security_conop/Introduction.rst, docs/security_conop/System_Management.rst, requirements.txt
Updated to use the latest version of Sphinx to work around some issues.
Fixed some documentation issues in the process.
SIMP-1165 #comment Updated python packages and fixed docs
=> (SIMP-1165) Doc updates and new Python packages

docs/conf.py, docs/installation_guide/index.rst
=> (SIMP-1524) fix headers for ReadTheDocs (version-release)

docs/contributors_guide/Contribution_Procedure.rst, docs/contributors_guide/Introduction.rst, docs/contributors_guide/Resources.rst, docs/contributors_guide/index.rst, docs/glossary.rst, docs/index.rst
Moved the Contribution Procedures from Confluence into the main
documentation.
SIMP-2042 #close
=> (SIMP-2042) Migrated in the Contribution Procs

docs/getting_started_guide/ISO_Build/Environment_Preparation.rst
Added a specific `yum install` for the EPEL installation or EL 6 and EL 7
SIMP-2117 #close
=> (SIMP-2117) Clearly specify EPEL installation

Gemfile, docs/contributors_guide/Contribution_Procedure.rst, docs/contributors_guide/Maintenance_Procedure.rst, docs/contributors_guide/Resources.rst, docs/contributors_guide/index.rst
We have moved our code review process to Github, and the old
Contributors guide needed to be updated.
SIMP-2053 #close
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/simp/simp-doc/129)
=> (SIMP-2053) New Contributors Guide

docs/contributors_guide/Maintenance_Procedure.rst
Needed to add a snippet on enabling pushes to updates.
SIMP-2257 #close
=> (SIMP-2257) Fix Maintenance Procedure

docs/getting_started_guide/Installation_Miscellaney.rst
=> (SIMP-2467) fix the table that caused RTD to fail

.gitignore, .travis.yml, Rakefile, docs/conf.py, docs/contributors_guide/Contribution_Procedure.rst, docs/contributors_guide/Resources.rst, docs/glossary.rst, docs/security_conop/Introduction.rst, docs/security_conop/Technical_Security.rst, docs/user_guide/HOWTO/Kerberos.rst, docs/user_guide/HOWTO/Puppet_Server_NAT.rst, docs/user_guide/Troubleshooting/Why_Cant_I_Login.rst
- Added rake docs:linkcheck which will check for broken external links
=> (SIMP-1551) Add rake task for checking links

docs/user_guide/Client_Management.rst, docs/user_guide/PXE_Boot.rst
=> (SIMP-2676) Fix tftpboot and dhcpd rsync paths

docs/help/FAQ.rst, docs/help/FAQ/Rsync.rst
=> (SIMP-2687) Add rsync justification to docs

docs/getting_started_guide/ISO_Install/SIMP_Server_Installation.rst, docs/getting_started_guide/Installing_SIMP_From_A_Repository.rst
First set of fixes, plus fix for links broken when
Installation Miscellany page was moved.
SIMP-2695 #close
=> (SIMP-2695) Fixes for RPM install docs - part 1

docs/user_guide/HOWTO/NFS.rst
=> (SIMP-2555) Update nfs docs to use simp_nfs

docs/getting_started_guide/ISO_Install/SIMP_Server_Installation.rst
Don't use Everything DVD in the SIMP server post install
YUM setup instructions.
SIMP-2717 #close
=> (SIMP-2717) Fix ISO name in SIMP server install

docs/user_guide/User_Management/Local_Users.rst
=> (SIMP-2678) Update advice on local users

docs/user_guide/HOWTO/Central_Log_Collection/Rsyslog.rst, docs/user_guide/Hiera_Overview.rst
-updated documentation for central log server
SIMP-2698 #comment Still want to put a warning in code for looping
=> (SIMP-2698) Update documentation for central log server

CHANGELOG, docs/getting_started_guide/ISO_Build/Building_SIMP_From_Source.rst, docs/getting_started_guide/ISO_Build/Building_SIMP_From_Tarball.rst, docs/getting_started_guide/ISO_Build/Building_SIMP_Via_Rake.rst, docs/getting_started_guide/ISO_Build/Environment_Preparation.rst
Added material to the docs to help users understand what the SIMP Dev
GPG keys do and how to use them after building an ISO.
SIMP-2714 #comment Updated docs for GPG move
SIMP-2752 #close
=> (SIMP-2714) Update documentation for SIMP Dev GPG

docs/getting_started_guide/Installing_SIMP_From_A_Repository.rst
Updated for SIMP 6
SIMP-2732 #close
=> (SIMP-2732) Fixed GPG keys in the docs

docs/getting_started_guide/Initial_Configuration.rst, docs/user_guide/HOWTO/Central_Log_Collection/Rsyslog.rst, docs/user_guide/Hiera_Overview.rst
Only merge IF corresponding changes to simp-core, pupmod-simp-simp, and rubygem-simp-cli are to be merged.
SIMP-2782 #close
=> (SIMP-2782) Update simp-lite doc refs to simp_lite

CHANGELOG, docs/conf.py, docs/glossary.rst
Also update the order of the build to build SIMP 6 (master) by default
SIMP-2812 #close
=> (SIMP-2812) Ignore false positives in linkcheck

README.md, Rakefile, build/simp-doc.spec
Fixed the dependencies for EL6 builds.
SIMP-2875 #close
=> (SIMP-2875) Updated to build properly on EL6

CHANGELOG, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/SSH_Restrict_Network_Access.rst
Added a HOWTO on restricting SSH access to specific hosts and networks.
SIMP-2897 #comment Updated HOWTO
SIMP-2905 #close
=> (SIMP-2897) Add HOWTO for network ssh restrictions

CHANGELOG, docs/user_guide/HOWTO/SFTP_Restricted_Accounts.rst
=> (SIMP-2928) Updated SFTP Restricted Account HOWTO

CHANGELOG, docs/user_guide/HOWTO/Redundant_LDAP.rst
=> (SIMP-2927) Updated Redundant LDAP HOWTO

CHANGELOG, docs/user_guide/HOWTO/IPTables_NAT_Rules.rst
=> (SIMP-2921) Updated IPTables NAT HOWTO

CHANGELOG, docs/glossary.rst, docs/user_guide/HOWTO/Central_Log_Collection/Rsyslog.rst
* Updated the rsyslog HOWTO
* Updated the Glossary
SIMP-2912 #close
=> (SIMP-2912) Rsyslog HOWTO Updates

CHANGELOG, docs/user_guide/HOWTO/Changing_Puppet_Masters.rst
* Updated the HOWTO
SIMP-2913 #close
=> (SIMP-2913) Updated HOWTO for Changing Servers

CHANGELOG, docs/glossary.rst, docs/user_guide/HOWTO/NFS.rst
* Updated the NFS HOWTO based on the latest module set
* Added YAMLL to the Glossary
SIMP-2920 #close
=> (SIMP-2920) Updated NFS HOWTO

docs/getting_started_guide/Initial_Configuration.rst
Updated all simp config info that has changed since last
release.
SIMP-2969 #close
=> (SIMP-2969) Update simp config YUM variables in simp doc

docs/user_guide/HOWTO/Managing_Workstation_Infrastructures.rst
- fixed some changes in libvirt sections
- add info to include packages that were not in default
SIMP-2264  #comment still need to llook through printer and VNC server
=> (SIMP-2264) UPdate Workstation Docs

CHANGELOG, docs/user_guide/HOWTO/Kerberos.rst
=> (SIMP-2922) Updated Kerberos HOWTO

CHANGELOG, docs/getting_started_guide/ISO_Build/Building_SIMP_From_Tarball.rst, docs/user_guide/HOWTO/Work_With_Rsync.rst
=> (SIMP-2988) Updated simp rsync howto

CHANGELOG, docs/user_guide/User_Management/Local_Users.rst
=> (SIMP-2985) Minor fixes to local_account template

docs/user_guide/HOWTO/Managing_Workstation_Infrastructures.rst, docs/user_guide/User_Management/LDAP.rst
=> (SIMP-3014) Fix typos in ldif and vm config filenames

CHANGELOG, docs/user_guide/Certificates.rst, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Changing_Puppet_Masters.rst, docs/user_guide/HOWTO/Puppetmaster_Backup.rst, docs/user_guide/HOWTO/Upgrade_SIMP.rst
=> (SIMP-2898) Created the recommended HOWTO Upgrade SIMP guide

docs/user_guide/HOWTO/Managing_Workstation_Infrastructures.rst
- added more information for managing workstations.
SIMP-704 #close
=> SIMP-704 Update Managing Workstation Doc

CHANGELOG, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Disable_Ssh.rst
=> (SIMP-3010) Added HOWTO disable SSH

CHANGELOG, docs/getting_started_guide/ISO_Install/SIMP_Server_Installation.rst
=> (SIMP-3273) Updated post-installation login docs

docs/conf.py, docs/getting_started_guide/Installing_SIMP_From_A_Repository.rst, docs/glossary.rst
Walked throug the guide on CentOS and RHEL at the same time and made
the process easier to understand for RHEL users.
SIMP-2213 #comment Updated to address RHEL
=> (SIMP-2213) Updates to address RHEL

CHANGELOG, docs/help/FAQ.rst, docs/help/FAQ/Selinux.rst
Add section on how to recover from boot failure with reason
'Failed to load SELINUX policy, freezing'
SIMP-3482 #close
=> (SIMP-3482) Add selinux policy failure advice

CHANGELOG, docs/conf.py, docs/user_guide/HOWTO/Upgrade_SIMP.rst
- Updated the user guide with instructions to back up legacy auth.conf
and modify new auth.conf, need be.
SIMP-3283 #comment done in docs
=> (SIMP-3283) user guide auth.conf updates

docs/contributors_guide/Testing_on_FIPS_Systems.rst, docs/contributors_guide/index.rst, docs/glossary.rst
* Added guidance
* Updated Glossary
SIMP-3431 #close
=> (SIMP-3431) Update docs for testing on FIPS system

CHANGELOG, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Modify_Puppet_Cron.rst
=> (SIMP-3298) Added a HOWTO modify puppet agent cron-job

CHANGELOG, docs/user_guide/HOWTO/Manage_TPM.rst
Add documentation on how to enable tboot using the PR in
simp/pupmod-simp-tpm#34
SIMP-3496 #close
=> (SIMP-3416) docs: Add tboot documentation

docs/help/FAQ.rst, docs/help/FAQ/Puppet.rst
Ensure that users know that they might encounter crashes from using
Facter 3.
SIMP-3362 #close
SIMP-3525 #close
=> (SIMP-3362) Added FACT-1732 material to FAQ

CHANGELOG, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/SNMPD.rst
- added HOW TO for snmpd
SIMP-3472 #close
=> (SIMP-3472) Add documents for SNMPD

CHANGELOG, docs/getting_started_guide/ISO_Install/SIMP_Server_Installation.rst
SIMP-3618 #comment docs updated
SIMP-3697 #close
=> (SIMP-3618) Updated hardware requirements

Gemfile, Rakefile, build/simp-doc.spec, docs/getting_started_guide/ISO_Build/Building_SIMP_From_Source.rst, docs/help/FAQ/Selinux.rst
* Docs no longer require mock
* Updated to support new directory structure
* Requires simp-rake-helpers 5+
SIMP-3633 #comment doc repo update
=> (SIMP-3633) Fix doc build without mock

CHANGELOG, docs/user_guide/HOWTO/Central_Log_Collection/Logstash.rst
- Note known problems
- Update dependency versions
- Clarify SIMP profile modules and the modules they use
- Inform user of paid security option available from Elasticsearch
for Elasticsearch node-to-node communication.
- Fix outdated hiera references
- Remove OBE hiera configuraion
- Fix formatting
SIMP-3813 #close
=> (SIMP-3813) Update Central_Log_Collection/Logstash.rst

.travis.yml, docs/conflib/release_mapping.py, docs/conflib/release_mapping_test.py
=> (SIMP-3838) doc: Run python tests in travis

CHANGELOG
SIMP-3811 #comment fixed issues found when building
=> (SIMP-3811) Put changelog in chronological order

docs/getting_started_guide/Installing_SIMP_From_A_Repository.rst
Update GPG list
* Update RPM-GPG-KEY-PGDG-94 to RPM-GPG-KEY-PGDG-96
* Add GPG-KEY-elasticsearch
* Add RPM-GPG-KEY-grafana
=> (SIMP-3855) simp-doc Update Installing_SIMP_From_A_Repository.rst

docs/getting_started_guide/ISO_Install/SIMP_Server_Installation.rst, docs/getting_started_guide/Initial_Configuration.rst
=> (SIMP-3846) simp-doc:Update GettingStarted/InitialConfiguration guide

docs/security_conop/Operational_Security.rst, docs/user_guide/HOWTO/Puppetmaster_Backup.rst
=> (SIMP-3930) Remove references to BackupPC

docs/contributors_guide/maintenance/iso_release_procedures/Pre_Release_Checklist.rst, docs/contributors_guide/maintenance/other_iso_related_project_release_procedures/Pre_Release_Checklist.rst, docs/contributors_guide/maintenance/ruby_gem_release_procedures/Pre_Release_Checklist.rst, docs/contributors_guide/maintenance/simp_puppet_module_release_procedures/Pre_Release_Checklist.rst
SIMP-3899 #comment Release procedures typos
=> (SIMP-3899) simp-doc : Fix release procedures typos

CHANGELOG, docs/getting_started_guide/ISO_Build/Environment_Preparation.rst
=> (SIMP-3957) Updated docker installation guide

CHANGELOG, docs/security_conop/Operational_Security.rst, docs/security_conop/evaluation_artifacts/SCAP.rst, docs/security_conop/evaluation_artifacts/SCAP/Report_Template.rst
* Added information on running SCAP scans on notional SIMP systems
* Added a response template for the SSG material
SIMP-3978 #comment Added SSG scan information
=> (SIMP-3978) SCAP Scan Information Update

Rakefile, docs/getting_started_guide/ISO_Build/Building_SIMP_From_Source.rst, docs/getting_started_guide/ISO_Build/Building_SIMP_From_Tarball.rst, docs/getting_started_guide/ISO_Build/Environment_Preparation.rst, docs/user_guide/Upgrade_SIMP/Version_Maps/6.0.0_6.1.0.inc
Fixed some glaring errors pre release
SIMP-4080 #close
=> (SIMP-4080) Final doc check and update

README.md, docs/getting_started_guide/Installing_SIMP_From_A_Repository.rst
Updated the GPG key list for the 'simp-dependencies' repository
SIMP-4107 #close
=> (SIMP-4107) Update GPG key list for simp-deps repo

docs/getting_started_guide/ISO_Install/SIMP_Server_Installation.rst, docs/getting_started_guide/SIMP_on_Amazon_Web_Services.rst, docs/getting_started_guide/index.rst
=> (SIMP-3284) Added SIMP on AWS to getting started

docs/user_guide/PXE_Boot.rst
-updated the docs to add procedures for
kickstarting machines in UEFI mode.
=> (Simp-4040) TFTPBOOT docs update

docs/contributors_guide/maintenance/Tagging_and_Releasing_Components.rst, docs/contributors_guide/maintenance/iso_release_procedures/Build_ISOs_and_Deploy_simp_project.rst, docs/contributors_guide/maintenance/iso_release_procedures/Notify_Mailing_List.rst, docs/contributors_guide/maintenance/iso_release_procedures/Pre_Release_Checklist.rst, docs/getting_started_guide/ISO_Build/Building_SIMP_From_Tarball.rst, docs/getting_started_guide/Installing_SIMP_From_An_ISO.rst, docs/getting_started_guide/SIMP_on_Amazon_Web_Services.rst, docs/security_conop/Operational_Security.rst, docs/user_guide/Upgrade_SIMP/General_Upgrade_Instructions.rst
- Removed OBE MCollective references.
- Fixed formatting errors.
- Updated to new URLs for SIMP artifacts
SIMP-4411 #comment Remove mcollective cruft from simp-doc
=> (SIMP-4411) Update docs to reflect removal of mcollective

docs/getting_started_guide/Installing_SIMP_using_r10k.rst, docs/user_guide/SIMP_Administration/Classification_and_Data/Assigning_Classes_to_Nodes.inc
=> (SIMP-4460) Mention simp-vendored-r10k in r10k docs

Rakefile, docs/help/FAQ.rst, docs/help/FAQ/Ssh.rst, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Configure_Ssh.rst
This patch adds an FAQ clarifying different scenarios for managing SSH
with SIMP.
SIMP-4481 #close #comment Added FAQ for customizing sshd_config
SIMP-4495 #close #comment Added FAQ for customizing ssh_config
=> (SIMP-4198) Add FAQ for configuring SSH

.travis.yml, docs/license.rst, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/IPA_Clients.rst, docs/user_guide/HOWTO/Manage_TPM.rst
Add prelimiary documentation on how a bulk host enrollment workflow
might look in SIMP. Code provided is probably bad and only for example.
SIMP-4857 #comment predocs added
=> (SIMP-4857) Add HOWTO for IPA enrollment workflow

docs/user_guide/HOWTO/IPA_Clients.rst
* Change class referenced to simp_ipa
* Add more advice
=> (SIMP-4918) Update IPA docs

docs/user_guide/Upgrade_SIMP/Version_Maps/6.1.0_6.2.0.inc
=> (SIMP-5117) Document logrotate.d changes in upgrade guide

docs/conf.py, docs/contributors_guide/Contribution_Procedure.rst, docs/glossary.rst, docs/user_guide/HOWTO/Kerberos.rst, docs/user_guide/User_Management/LDAP.rst, docs/vulnerability_supplement/Stack_Clash.rst
Added text reflecting the current working state of how changes are
processed through the system.
=> (SIMP-MAINT) Updated contribution guide

docs/user_guide/PXE_Boot.rst, docs/user_guide/Upgrade_SIMP/Version_Maps/6.1.0_6.2.0.inc
Reword a section for clarity
SIMP-5118 #close
=> (SIMP-5118) Update upgrade guide

docs/user_guide/HOWTO/Managing_Workstation_Infrastructures.rst, docs/user_guide/PXE_Boot.rst
=> (SIMP-5217) Fix bug in example tftpboot puppet code

docs/glossary.rst, docs/help/FAQ/Selinux.rst, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Managing_Workstation_Infrastructures.rst, docs/user_guide/HOWTO/NFS.rst, docs/user_guide/HOWTO/Work_With_Rsync.rst
- Updated workstation infrastructure
- Added examples to NFS
- Moved SSH entries together in index
SIMP-5271 #comment Still in Progress
=> (SIMP-5271) SIMP 6.2 Docs Updates

CHANGELOG, docs/changelogs/latest.rst, docs/user_guide/HOWTO/Central_Log_Collection/Logstash.rst
Added information about the removal of the ELG RPMs from the ISO.
SIMP-5471 #close
=> (SIMP-5441) Add information about removing ELG rpms

docs/getting_started_guide/Installation_Options/ISO/ISO_Build/Building_SIMP_From_Source.rst, docs/getting_started_guide/Installation_Options/ISO/ISO_Build/Environment_Preparation.rst, docs/getting_started_guide/Installation_Options/ISO/Installing_SIMP_From_An_ISO.rst, docs/help/FAQ/00_SIMP_Version_Guide.rst, docs/user_guide/Client_Management.rst, docs/user_guide/PXE_Boot.inc, docs/user_guide/SIMP_Administration/General_Administration/Certificate_Management.inc
fixed pipe issue for version guide, and moved info about KS to the KS section fo 4.4.1
fixed spelling issues and updated some code sections 
fixed NOTE formatting
SIMP-5757 #close
=> (SIMP-5757) Fixing documentation.

docs/user_guide/HOWTO/Managing_Workstation_Infrastructures.rst
- added sample configs for x2go/mate config in workstation management
SIMP-5447 #close
SIMP-5224 #comment x2go/mate update complete.
=> (SIMP-5224) 6.3 Doc update

docs/changelogs/latest.rst, docs/user_guide/Upgrade_SIMP/Version_Maps/6.2.0_6.3.0.inc
- update the change log for SIMP 6.3
SIMP-5578 # close
=> (SIMP-5578) 6.3 Changelog

docs/user_guide/HOWTO/NFS.rst
- Added a warning to grab attention
- Fixed broken links to old autofs versions
SIMP-5844 #close
=> (SIMP-5844) Updated NFS HowTo to highlight autofs bugs

docs/user_guide/Upgrade_SIMP/Version_Maps/6.2.0_6.3.0.inc
- update the Version_map file for upgrading from
SIMP 6.2 to SIMP 6.3
SIMP-5577 #comment Docs are updated.
=> (SIMP-5577) 6.3.0 Specific Upgrade Document

CHANGELOG, docs/index.rst, docs/user_guide/Upgrade_SIMP/Version_Maps/6.2.0_6.3.0.inc
- Added warning about copy/paste and quotes
- Added a note to restart puppetdb to the 6.2->6.3 upgrade guide
SIMP-5607 #comment PuppetDB restart notes
=> (SIMP-5607) Upgrade Notes

docs/changelogs/latest.rst, docs/user_guide/HOWTO/Managing_Workstation_Infrastructures.rst, docs/user_guide/HOWTO/NFS.rst, docs/user_guide/PXE_Boot.inc, docs/user_guide/SIMP_Administration/General_Administration/Graphical_User_Interfaces.inc, docs/user_guide/Upgrade_SIMP/Version_Maps/6.1.0_6.2.0.inc, docs/user_guide/Upgrade_SIMP/Version_Maps/6.2.0_6.3.0.inc
Minor clean up of the Changelog and update to the `tlog` section to
address the last few changes
Fixed formatting bugs
SIMP-5885 #close
=> (SIMP-5885) Finalize 6.3.0-0 docs

CHANGELOG, docs/user_guide/Upgrade_SIMP/Version_Maps/6.2.0_6.3.0.inc, docs/user_guide/Upgrade_SIMP/Version_Maps/6.3.0_6.3.2.inc, docs/user_guide/Upgrade_SIMP/Version_Specific_Upgrade_Instructions.rst
=> (SIMP-6063) Finalize documentation for 6.3.2

CHANGELOG, docs/changelogs/6.3.2_Changelog.rst, docs/changelogs/latest.rst, docs/contributors_guide/Contribution_Procedure.rst, docs/contributors_guide/maintenance/Amending_Pull_Requests.rst, docs/security_conop/Operational_Security.rst, docs/user_guide/Upgrade_SIMP/Version_Maps/6.3.2_6.3.3.inc, docs/user_guide/User_Management/Local_Users.rst, docs/user_guide/User_Management/SSSD.rst
=> (SIMP-6153) Documentation updates for 6.3.3

CHANGELOG, docs/getting_started_guide/Installation_Options/ISO/Installation_Advanced_Topics/Disk_Partitioning.rst, docs/getting_started_guide/Installation_Options/ISO/Installation_Advanced_Topics/index.rst, docs/security_mapping/components/apache/transmission_confidentiality_and_integrity/control.rst
Updated 7.1.3.8 Transmission Confidentiality and Integrity to reflect
the correct location of the certificates.
=> (SIMP-6329) Updated certificate location

docs/changelogs/latest.rst
SIMP-6190 #close
SIMP-6192 #close
=> (SIMP-6190) Update simp-doc with simp-adapter changes

docs/changelogs/latest.rst, docs/glossary.rst
SIMP-6404 #close
SIMP-6405 #close
SIMP-6403 #close
=> (SIMP-6404) First pass at SIMP 6.4.0 changelog

CHANGELOG, docs/glossary.rst
=> (SIMP-6702) Fix link to DISA STIGs

CHANGELOG, docs/help/FAQ/10_Password_Complexity.rst, docs/user_guide/Client_Management.rst, docs/user_guide/HOWTO/SNMPD.rst
* Updated the password complexity FAQ to note the new settings as well
as give some examples for items that routinely confuse users.
* Fix a link and some spelling issues in the Client Management section
of the User's Guide.
SIMP-6667 #close
=> (SIMP-6667) Update Password Complexity FAQ

docs/conflib/release_mapping.py
The `yaml.full_load` method is only available in PyYaml 5.1+ (released 13 
Mar 2019).  When used with earlier versions, python crashes and Sphinx 
does not compile.
This patch provides a helper that uses `yaml.full_load` when 
PyYaml >= 5.1 and `yaml.load` for earlier versions.
See: https://stackoverflow.com/a/55553392
=> (SIMP-MAINT) Use legacy `.load` when yaml < 5.1

Rakefile
This patch updates `rake docs:server` to execute [`sphinx-autobuild`][0],
if it is available:
* If `sphinx-autobuild` is available, it will be used to provide a
live-reload- capable web server that recompiles and refreshes the
browser whenever a file is edited.
* Otherwise, the docs will be auto-compiled (just once) using `rake docs:html`
and then served using `ruby -run -e httpd`
[0]: https://pypi.org/project/sphinx-autobuild/
=> (SIMP-MAINT) docs:server prefers sphinx-autobuild

docs/glossary.rst, docs/user_guide/HOWTO/Bolt.rst
Added the specific verbiage from the NIST policies to the Bolt
'non-phone home' docs.
This will probably be reused over time so added it to the Glossary.
=> (SIMP-6784) Add NIST phone-home info

docs/user_guide/HOWTO/NFS.rst
=> (SIMP-6729) Update autofs stunnel docs

docs/help/FAQ/00_SIMP_Version_Guide.rst, docs/help/FAQ/10_Password_Complexity.rst, docs/help/FAQ/40_Audit_Syslog.rst, docs/help/FAQ/Puppet.rst, docs/help/FAQ/Selinux.rst, docs/help/FAQ/Yum_Repo_Issues.rst
=> (SIMP-6819) Tweak descriptions in FAQs

docs/user_guide/HOWTO/Control_Nightly_Update_Schedule.rst, docs/user_guide/HOWTO/Discard_Mail_to_Root.rst, docs/user_guide/HOWTO/Exclude_Repositories.rst, docs/user_guide/HOWTO/Modify_Puppet_Cron.rst, docs/user_guide/HOWTO/SSH_Keys.rst
Update a few of the HOWTOs
SIMP-6818 #comment 5 HOWTOs updated
=> (SIMP-6818) Update HOWTOs part 1

.gitignore, docs/user_guide/HOWTO/Disable_Ssh.rst, docs/user_guide/HOWTO/Kerberos.rst, docs/user_guide/HOWTO/SNMPD.rst, docs/user_guide/SIMP_Administration/Classification_and_Data/Assigning_Classes_to_Nodes.inc
SIMP-6618 #comment 3 more HOWTOs
=> (SIMP-6818) Update 3 more HOWTOs

docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Central_Log_Collection.rst, docs/user_guide/HOWTO/Central_Log_Collection_with_Rsyslog.rst
=> (SIMP-6873) Review Set up Centrol Log Collection

docs/glossary.rst, docs/user_guide/Upgrade_SIMP/General_Upgrade_Instructions.rst
- updated General Upgrade procedures for upgrades after
SIMP 6.4.0.
SIMP-6210 #close
SIMP-6579 #comment  General Upgrade Procedure Updated.
=> (SIMP-6210) Update General Upgrade procedures

docs/contributors_guide/maintenance/iso_release_procedures/Pre_Release_Checklist.rst, docs/user_guide/HOWTO/IPA_Clients.rst
=> (SIMP-6870) Update IPA host enroll HOWTO

docs/glossary.rst, docs/user_guide/Client_Management.rst, docs/user_guide/HOWTO/Changing_Puppet_Masters.rst
* Changed terminology to reflect Puppet agents and SIMP environments
* Updated links to relevant documentation sections and glossary terms
* Updated Hiera archive command with faster `find` arguments
* Added extra Hiera notes for users with control repositories
* Reorganized sections and updated copy to clarify procedure's intent
* Removed outdated note about SIMP-3049
* Changed `puppet_reload` to `puppet reload`
SIMP-6874 #close
=> (SIMP-6874) Review Change Puppet Masters HOWTO

docs/glossary.rst, docs/user_guide/HOWTO/Changing_Puppet_Masters.rst, docs/user_guide/SIMP_Administration/Classification_and_Data/SIMP_Compliance_Engine.inc
* Corrected NIST profile
* Added section on how to discover what profiles are available
SIMP-6871 #close
=> (SIMP-6871) Update Compliance Engine Docs

docs/glossary.rst, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Changing_Puppet_Masters.rst, docs/user_guide/HOWTO/Control_Repo.rst, docs/user_guide/Initial_Server_Configuration.rst, docs/user_guide/SIMP_Administration/Environments.rst, docs/user_guide/SIMP_Administration/Environments/SIMP_CLI_Environment_Management.inc
=> (SIMP-6615) Rework HOWTO Set up a Control Repository

docs/user_guide/Initial_Server_Configuration/Prevent_Lockout_on_Puppetserver.inc
Fix a path to the created module that I missed in the first review.
=> (SIMP-6579) Fix path in Configure Local User for Access

docs/user_guide/HOWTO/Configure_Ssh.rst
=>  (SIMP-6899) Document SSH multiple port support

docs/changelogs/latest.rst
=> (SIMP-6940) Update the docs with changes since RC1

docs/changelogs/latest.rst, docs/help/FAQ/Puppet.rst
Also incorporated judyj fix for rendering problem
SIMP-6939 #close
=> (SIMP-6939) Update compliance_markup changelog entry

docs/changelogs/latest.rst
My OCD is out of control!
SIMP-7072 #close
=> (SIMP-7072) Fix 6.4.0-RC1 Changelog to 6.4.0-0

docs/conf.py, docs/contributors_guide/Contribution_Procedure.rst, docs/contributors_guide/maintenance/Amending_Pull_Requests.rst, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Enable_STIG_Mode.rst, docs/user_guide/User_Management/SSSD.rst
* Add specific STIG mode instructions
* Fix linkcheck issues
* Fix pylint warnings in conf.py
* Ignore qualys.com links in linkcheck since they're often broken
SIMP-7187 #close
=> (SIMP-7187) Add STIG mode instructions

docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Block_or_Cache_Facts.rst
=> (SIMP-5952) Document facter config management

CHANGELOG, docs/help/FAQ/Logrotate.rst
=> [SIMP-7257] Add FAQ on duplicate logrotate entries

CHANGELOG, docs/user_guide/User_Management/SSSD.rst
* Remove references to the 'local' provider
* Add references to the 'files' provider for those that need the
functionality
=> [SIMP-7240] Update SSSD Docs

docs/contributors_guide/maintenance/ISO_Release_Procedures.rst, docs/contributors_guide/maintenance/Other_ISO_Related_Project_Release_Procedures.rst, docs/contributors_guide/maintenance/Other_Puppet_Module_Release_Procedures.rst, docs/contributors_guide/maintenance/SIMP_Puppet_Module_Release_Procedures.rst, docs/contributors_guide/maintenance/Tagging_and_Releasing_Components.rst, docs/contributors_guide/maintenance/common/Build_RPM_and_Deploy.inc, docs/contributors_guide/maintenance/iso_release_procedures/Build_simp_core_RPM_and_Deploy.rst, docs/contributors_guide/maintenance/iso_release_procedures/Notify_Mailing_List.rst, docs/contributors_guide/maintenance/iso_release_procedures/Pre_Release_Checklist.rst, docs/contributors_guide/maintenance/iso_release_procedures/Release_simp_core_GitHub_and_Deploy_PuppetForge.rst, docs/contributors_guide/maintenance/other_iso_related_project_release_procedures/Build_RPM_and_Deploy_packagecloud.rst, docs/contributors_guide/maintenance/other_iso_related_project_release_procedures/Pre_Release_Checklist.rst, docs/getting_started_guide/Installation_Options/Repository/Installing_SIMP_From_A_Repository.rst, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Using_the_SIMP_Release_RPM.rst, docs/user_guide/Upgrade_SIMP/General_Upgrade_Instructions.rst
Updates the simp-doc files to change PackageCloud references to the SIMP Download Server
[SIMP-7489] #close
[SIMP-7489]: https://simp-project.atlassian.net/browse/SIMP-7489
=> (SIMP-7489) Update Yum Locations

CHANGELOG, docs/glossary.rst, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Enable_Core_Dumps.rst
=> [SIMP-7809] Add HOWTO Enable Core Dumps

docs/conf.py, docs/contributors_guide/maintenance/Other_ISO_Related_Project_Release_Procedures.rst, docs/contributors_guide/maintenance/iso_release_procedures/Build_simp_core_RPM_and_Deploy_packagecloud.rst, docs/getting_started_guide/Installation_Options/ISO/ISO_Build/Building_SIMP_From_Source.rst, docs/getting_started_guide/Installation_Options/Repository/Installing_SIMP_From_A_Repository.rst, docs/getting_started_guide/System_Requirements.rst, docs/glossary.rst, docs/help/FAQ/Selinux.rst, docs/help/FAQ/Yum_Repo_Issues.rst, docs/user_guide/HOWTO/Using_the_SIMP_Release_RPM.rst, docs/user_guide/Upgrade_SIMP/General_Upgrade_Instructions.rst
Remove some warnings and bad links
=> (doc-fix)  

docs/user_guide/HOWTO/Enable_STIG_Mode.rst
`compliance_markup::enforcement` is an array.
SIMP-8132 #close
=> (SIMP-8132) Correct Compliance Engine documentation

docs/contributors_guide/maintenance/other_iso_related_project_release_procedures/Release_GitHub.rst
Second attempt to update the asset release procedures.
=> (SIMP-MAINT) Update asset release procedures

.readthedocs.yaml, docs/glossary.rst, docs/help/FAQ/Omni_Env_Exists.rst, requirements.txt
Changed text - feel free to comment and then un-WIP it
Note: 
I forgot I had done some test changes in the requirements.txt, where I eliminated almost all the files because they pull in their own prereqs. 
I also have the fix for .readthedocs.yaml in there, as I was testing it concurrently and forgot to undo it.
SIMP-8376 #close
=> (SIMP- 8376) Add a FAQ item around the omni environment already exists error

docs/contributors_guide/Contribution_Procedure.rst, docs/contributors_guide/Resources.rst, docs/contributors_guide/maintenance/iso_release_procedures/Pre_Release_Checklist.rst, docs/contributors_guide/maintenance/iso_release_procedures/Release_simp_core_GitHub_and_Deploy_PuppetForge.rst, docs/contributors_guide/maintenance/other_iso_related_project_release_procedures/Pre_Release_Checklist.rst, docs/contributors_guide/maintenance/other_iso_related_project_release_procedures/Release_GitHub.rst, docs/contributors_guide/maintenance/ruby_gem_release_procedures/Pre_Release_Checklist.rst, docs/contributors_guide/maintenance/ruby_gem_release_procedures/Release_GitHub_Deploy_RubyGems_org.rst, docs/contributors_guide/maintenance/simp_puppet_module_release_procedures/Pre_Release_Checklist.rst, docs/contributors_guide/maintenance/simp_puppet_module_release_procedures/Release_GitHub_and_Deploy_PuppetForge.rst
=> (SIMP-8391) Update links from travis-ci.org to travis-ci.com

CHANGELOG, docs/conflib/release_mapping.py, docs/contributors_guide/Contribution_Procedure.rst, docs/contributors_guide/maintenance/Amending_Pull_Requests.rst, docs/glossary.rst, docs/user_guide/HOWTO.rst, docs/user_guide/HOWTO/Manage_TPM.rst, docs/user_guide/HOWTO/Manage_reboot_notify.rst, docs/user_guide/User_Management/Local_Users.rst
* Added:
* HOWTO entry for managing simplib::reboot_notify notifications
SIMP-7798 #close
=> (SIMP-7798) Added HOWTO for simplib::reboot_notify

docs/common/Level_of_Knowledge.rst
This patch modernizes some outdated version numbers, adds term links for
consistency, and applies some wordsmithing to awkward passages.
=> (SIMP-MAINT) Modernize Level of Knowledge section

docs/changelogs/latest.rst
Add a note to the changelog for the most recent change to compliance_markup.
SIMP-8448 #comment
=> (SIMP-8448) Update changelog for SIMP 6.5.0

docs/user_guide/Initial_Server_Configuration/Prevent_Lockout_on_Puppetserver.inc
Fixed:
* Replaced the module creation, etc... with a short YAML snippet
SIMP-8573 #close
=> (SIMP-8572) Refactor the lockout docs

docs/user_guide/Upgrade_SIMP/General_Upgrade_Instructions.rst
=> (SIMP-8477) Upgrade instructions should temporarily disable puppet agent

docs/changelogs/latest.rst
Updated changelogs to reflect the following:
* pupmod-simp-libreswan 3.4.0
* pupmod-simp-simp 4.13.0
* pupmod-simp-simplib 4.6.0
* pupmod-simp-tpm2 0.3.1
* rubygem-simp-cli 6.0.2-6.1.1
* simp-utils 6.3.0
SIMP-8480 #comment partial update
=> (SIMP-8480) Changelog updates for bug fixes

docs/user_guide/Certificates/Certificates.inc, docs/user_guide/Certificates/Official_Certificates.inc, docs/user_guide/Client_Management.rst, docs/user_guide/PXE_Boot.inc
This patch adds role-based formatting to Client Management docs.
=> (SIMP-MAINT) Convert Client Management to roles

docs/_extensions/simp_roles.py, docs/changelogs/6.1.0_Changelog.rst, docs/changelogs/latest.rst, docs/vulnerability_supplement/Stack_Clash.rst
Added:
* Added information on the iptables precise matching
* Added a role for CVEs and updated the entries in the docs
SIMP-8640 #close
=> (SIMP-8640) Add information on precision iptables

docs/changelogs/latest.rst
Updates for the following components:
* pupmod-simp-libreswan 3.4.1
* pupmod-simp-pupmod 8.1.2
* pupmod-simp-rsyslog 7.6.4
* pupmod-simp-simp 4.14.1
* pupmod-simp-simplib 4.6.1
* pupmod-simp-simp_rsyslog 0.5.1
* simp-environment-skeleton 7.2.0
SIMP-8644 #comment part1
=> (SIMP-8644) Changelog updates part 1

docs/changelogs/latest.rst
Update for simp-adapter 2.0.0 and fix typo identified
but not fixed in an earlier PR.
SIMP-8476 #close
=> (SIMP-8476) Update changelog for simp-adapter 2.0.0

docs/changelogs/latest.rst
[SIMP-8644] #comment part 4
[SIMP-8644]: https://simp-project.atlassian.net/browse/SIMP-8644
=> (SIMP-8644) Update changelog for simp_snmpd

docs/changelogs/latest.rst
=> (SIMP-8644) Changelog entry for kickstart file bugfix

docs/changelogs/latest.rst
- made some updates to the simp_snmpd entry in the changelog.
=> (SIMP-8644) changelog simp_snmpd entry

docs/changelogs/latest.rst
Update for simp-utils 6.4.0
SIMP-8644 #comment part2
=> (SIMP-8644) Update changelog for 1 component

docs/changelogs/latest.rst
simp_apache 7.0.1
simp_gitlab 0.6.0
SIMP-8644 #close
=> (SIMP-8644) Changelog entries for 2 components

docs/HOWTO/00_Accounts_and_Access/Configure_Ssh.rst, docs/HOWTO/00_Accounts_and_Access/Disable_Ssh.rst, docs/HOWTO/00_Accounts_and_Access/IPA_Clients.rst, docs/HOWTO/00_Accounts_and_Access/Redundant_LDAP.rst, docs/HOWTO/00_Accounts_and_Access/SFTP_Restricted_Accounts.rst, docs/HOWTO/00_Accounts_and_Access/SSH_Keys.rst, docs/HOWTO/00_Accounts_and_Access/SSH_Restrict_Network_Access.rst, docs/HOWTO/00_Accounts_and_Access/index.rst, docs/HOWTO/10_SIMP/Alternate_SIMP_Config_Environment.rst, docs/HOWTO/10_SIMP/Compliance_Enforcement.rst, docs/HOWTO/10_SIMP/Disable_the_Firewall.rst, docs/HOWTO/10_SIMP/Enable_STIG_Mode.rst, docs/HOWTO/10_SIMP/Generate_SIMP_Puppetfile.rst, docs/HOWTO/10_SIMP/Manage_reboot_notify.rst, docs/HOWTO/10_SIMP/Managing_Workstation_Infrastructures.rst, docs/HOWTO/10_SIMP/Modify_Puppet_Cron.rst, docs/HOWTO/10_SIMP/Upgrade_SIMP.rst, docs/HOWTO/10_SIMP/Using_the_SIMP_Release_RPM.rst, docs/HOWTO/10_SIMP/index.rst, docs/HOWTO/20_Puppet/Block_or_Cache_Facts.rst, docs/HOWTO/20_Puppet/Changing_Puppet_Masters.rst, docs/HOWTO/20_Puppet/Control_Repo.rst, docs/HOWTO/20_Puppet/Disconnect_PuppetDB_from_Puppet_Server.rst, docs/HOWTO/20_Puppet/ENC_setup.rst, docs/HOWTO/20_Puppet/Migrate_to_New_Puppet_Server.rst, docs/HOWTO/20_Puppet/Puppetmaster_Backup.rst, docs/HOWTO/20_Puppet/index.rst, docs/HOWTO/90_Misc/Manage_TPM.rst, docs/HOWTO/90_Misc/index.rst
=> (SIMP-8656) HOWTOs have inconsistent naming

docs/changelogs/latest.rst
Updates for:
* simp/iptables 6.5.4
* simp/selinux 2.6.1, 2.6.2
* simp/simp 4.14.3
=> (SIMP-MAINT) Changelog updates for 3 RC1 fixes

docs/changelogs/latest.rst
Updated changelog:
* simp/ssh 6.11.2
* simp/auditd 8.6.2
* simp-utils 6.5.0
=> (SIMP-MAINT) 3 component changelog updates

CHANGELOG
[SIMP-8824] #close
[SIMP-8824]: https://simp-project.atlassian.net/browse/SIMP-8824
=> (SIMP-8824) Update changelog

docs/HOWTO/20_Puppet/Hiera_eyaml.rst, docs/_static/css_overrides.css, docs/glossary.rst
- add HOWTO for setting up eyaml in SIMP puppet environments.
SIMP-8641 #close
=> (SIMP-8641) EYAML

.github/workflows/pr_glci.yml, .github/workflows/pr_glci_cleanup.yml, .github/workflows/pr_glci_manual.yml
[SIMP-9760] #close
[SIMP-9760]: https://simp-project.atlassian.net/browse/SIMP-9760
=> (SIMP-9760) Add GHA-triggered GLCI pipeline

CHANGELOG, docs/changelogs/latest.rst, docs/user_guide/User_Management/LDAP.rst, docs/user_guide/User_Management/LDAP/389_DS.rst, docs/user_guide/User_Management/LDAP/389_DS/cheat_sheet.rst, docs/user_guide/User_Management/LDAP/389_DS/manage_groups.rst, docs/user_guide/User_Management/LDAP/389_DS/manage_users.rst
Added information on managing accounts in 389-DS
SIMP-10188 #close
SIMP-10189 #close
=> (SIMP-10188) 389-DS Account Management

docs/HOWTO/00_Accounts_and_Access/Redundant_LDAP.rst, docs/HOWTO/20_Puppet/Block_or_Cache_Facts.rst, docs/HOWTO/20_Puppet/Hiera_eyaml.rst, docs/HOWTO/90_Misc/Unpack_dvd.rst, docs/changelogs/6.5.0_Changelog.rst, docs/getting_started_guide/Installation_Options/ISO/ISO_Build/Building_SIMP_From_Tarball.rst, docs/user_guide/Initial_Server_Configuration.rst, docs/user_guide/Initial_Server_Configuration/Prevent_Lockout_on_Puppetserver.inc, docs/user_guide/SIMP_Administration/Classification_and_Data/SIMP_Scenarios.inc, docs/user_guide/SIMP_Administration/Environments/Environments_Examples.inc, docs/user_guide/Upgrade_SIMP/Version_Maps/6.3.3_6.4.0.inc, docs/user_guide/User_Management/LDAP/389_DS/manage_groups.rst
(SIMP-MAINT) Periodic review of new changes.
=> (SIMP-MAINT) Grammar and spelling sanity check

docs/user_guide/User_Management/LDAP/389_DS/cheat_sheet.rst, docs/user_guide/User_Management/LDAP/389_DS/manage_groups.rst, docs/user_guide/User_Management/LDAP/389_DS/manage_users.rst
* Fixed
* Added `-b "<base DN>"` to the command line in all dsidm commands
SIMP-10427 #close
=> (SIMP-10427) Fix dsidm commands

CHANGELOG, docs/HOWTO/20_Puppet/Disconnect_PuppetDB_from_Puppet_Server.rst, docs/HOWTO/20_Puppet/Enable_Client_Reporting.rst, docs/conf.py, docs/contributors_guide/Contribution_Procedure.rst, docs/contributors_guide/Resources.rst, docs/contributors_guide/maintenance/iso_release_procedures/Pre_Release_Checklist.rst, docs/contributors_guide/maintenance/iso_release_procedures/Release_simp_core_GitHub_and_Deploy_PuppetForge.rst, docs/contributors_guide/maintenance/other_iso_related_project_release_procedures/Pre_Release_Checklist.rst, docs/contributors_guide/maintenance/other_iso_related_project_release_procedures/Release_GitHub.rst, docs/contributors_guide/maintenance/ruby_gem_release_procedures/Pre_Release_Checklist.rst, docs/contributors_guide/maintenance/ruby_gem_release_procedures/Release_GitHub_Deploy_RubyGems_org.rst, docs/contributors_guide/maintenance/simp_puppet_module_release_procedures/Pre_Release_Checklist.rst, docs/contributors_guide/maintenance/simp_puppet_module_release_procedures/Release_GitHub_and_Deploy_PuppetForge.rst, docs/glossary.rst
- Add HOWTO for enabling client reports
- Removed obsolete references to Travis CI
SIMP-9665 #comment Add HOWTO for enabling client reporting
=> (SIMP-9665) HOWTO Enable Client Reporting

CHANGELOG, docs/HOWTO/20_Puppet/Enable_Client_Reporting.rst, docs/HOWTO/20_Puppet/Enable_PuppetDB.rst
=> (SIMP-10449) Add HOWTO enable puppetdb

CHANGELOG, build/simp-doc.spec
=> Add 'dist' tag to the RPM

docs/HOWTO/10_SIMP/Using_the_SIMP_Release_RPM.rst
- Update simp-release docs to reference separate el7 and el8 paths
closes #454
=> Update simp-release install docs
